// Mocks generated by Mockito 5.3.2 from annotations
// in sib_sharing_session_project/test/provider/api_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sib_sharing_session_project/model/album.dart' as _i3;
import 'package:sib_sharing_session_project/service/api_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlbum_1 extends _i1.SmartFake implements _i3.Album {
  _FakeAlbum_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);
  @override
  _i5.Future<_i3.Album> fetchAlbum() => (super.noSuchMethod(
        Invocation.method(
          #fetchAlbum,
          [],
        ),
        returnValue: _i5.Future<_i3.Album>.value(_FakeAlbum_1(
          this,
          Invocation.method(
            #fetchAlbum,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Album>);
  @override
  _i5.Future<_i3.Album> fetchError() => (super.noSuchMethod(
        Invocation.method(
          #fetchError,
          [],
        ),
        returnValue: _i5.Future<_i3.Album>.value(_FakeAlbum_1(
          this,
          Invocation.method(
            #fetchError,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Album>);
}
